#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Agente de VMware para el portapapeles y resolución (MUY IMPORTANTE)
/usr/bin/vmware-user-suid-wrapper &

# Gestor de portapapeles para evitar que se pierda al cerrar ventanas
xclip &

# Fondo de pantalla
/usr/bin/feh --bg-fill $HOME/Dnk29/Fondos/Fondo.jpg &

# Polybar
~/.config/polybar/./launch.sh &

# Picom
picom &
